ARG PYTHON_VERSION=3.10
ARG BEAM_VERSION=2.49.0

FROM apache/beam_python${PYTHON_VERSION}_sdk:${BEAM_VERSION}

ENV PYTHONPATH src:
ENV WORKDIR /app/

WORKDIR $WORKDIR

COPY pyproject.toml poetry.lock $WORKDIR
COPY src src

RUN pip install --upgrade pip && \
    pip install -U poetry --no-cache-dir
RUN poetry config virtualenvs.create false && \
    poetry install --without dev --no-interaction --no-ansi
RUN python -m unidic download
