defaults:
  - _self_
  - runner: direct
  - dest: null

project_id: ${oc.env:PROJECT_ID}
project_name: ${oc.env:PROJECT_NAME}
region: ${oc.env:REGION}
temp_location: gs://${project_name}/temp
staging_location: gs://${project_name}/staging
data_dir: ../data-source/data

locale: jp
index_name: products_${locale}
nrows: 10

encode_text: False
table_id: docs_jp