.PHONY download
download:
	curl -L -O https://github.com/amazon-science/esci-data/blob/main/shopping_queries_dataset/shopping_queries_dataset_sources.csv
	curl -L -O https://github.com/amazon-science/esci-data/raw/refs/heads/main/shopping_queries_dataset/shopping_queries_dataset_examples.parquet
	curl -L -O https://github.com/amazon-science/esci-data/raw/refs/heads/main/shopping_queries_dataset/shopping_queries_dataset_products.parquet
