services:
  es-8:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.2
    container_name: amazon-product-search-es8
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ports:
      - 9200:9200
    volumes:
      - es-data:/usr/share/elasticsearch/8/data

  kibana-8:
    depends_on:
      - es-8
    image: docker.elastic.co/kibana/kibana:8.16.2
    container_name: amazon-product-search-kibana8
    ports:
      - 5602:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://es-8:9200

volumes:
  es-data:
    driver: local
