FROM docker.elastic.co/elasticsearch/elasticsearch:8.17.3

# Install the Elasticsearch plugin
RUN ./bin/elasticsearch-plugin install --batch https://github.com/o19s/elasticsearch-learning-to-rank/releases/download/v1.5.10-es8.17.3/ltr-plugin-v1.5.10-es8.17.3.zip