from invoke import task

from amazon_product_search.synonyms import generator


@task
def generate(c, model_name, output_filename):
    """Generate synonyms from query-title pairs.

    The synonym files in the data/includes were generated by the following commands.

    ```
    $ inv synonyms.generate --output-filename=synonyms_jp_sbert.csv
    $ inv synonyms.generate \
        --model-name=./models/jp_fine_tuned_sbert \
        --output-filename=synonyms_jp_fine_tuned_sbert.csv
    ```
    """
    generator.generate(model_name, output_filename)
