from invoke import task

from amazon_product_search.core.synonyms import generator


@task
def generate(c, locale, output_filename):
    """Generate synonyms from query-title pairs.

    The synonym files in the data/includes were generated by the following commands.

    ```
    $ inv synonyms.generate --output-filename=synonyms_jp_sbert.csv
    $ inv synonyms.generate \
        --locale=jp \
        --output-filename=synonyms_jp_fine_tuned_sbert.csv
    ```
    """
    generator.generate(locale, output_filename)
