services:
  # https://docs.vespa.ai/en/operations-selfhosted/multinode-systems.html
  # https://docs.vespa.ai/en/operations-selfhosted/files-processes-and-ports.html
  vespa-0:
    image: vespaengine/vespa:8.301.19
    container_name: amazon-product-search-vespa-0
    hostname: amazon-product-search-vespa-0.vespanet
    networks:
      - vespanet
    ports:
      - 19071:19071
      - 19100:19100
      - 19050:19050
      - 20092:19092
    command: configserver,services
    healthcheck:
      test: curl http://localhost:19071/state/v1/health
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - vespa-data-0:/opt/vespa/var
    environment:
      VESPA_CONFIGSERVERS: amazon-product-search-vespa-0.vespanet

  vespa-1:
    image: vespaengine/vespa:8.301.19
    container_name: amazon-product-search-vespa-1
    hostname: amazon-product-search-vespa-1.vespanet
    networks:
      - vespanet
    command: services
    depends_on:
      vespa-0:
        condition: service_healthy
    ports:
      - 8080:8080
      - 19107:19107
      - 19092:19092
    volumes:
      - vespa-data-1:/opt/vespa/var
    environment:
      VESPA_CONFIGSERVERS: amazon-product-search-vespa-0.vespanet

volumes:
  vespa-data-0:
    driver: local
  vespa-data-1:
    driver: local

networks:
  vespanet:
    driver: bridge
    name: vespanet
