# -------------------------------------
#  Execution Commands
# -------------------------------------
.PHONY: run_eda
run_eda:
	poetry run streamlit run src/demo/apps/eda/📊_Product_Catalogue.py

.PHONY: run_tokenization
run_features:
	poetry run streamlit run src/demo/apps/features/🤖_Tokenization.py

.PHONY: run_es
run_es:
	poetry run streamlit run src/demo/apps/es/🔍_Retrieval.py

.PHONY: run_vespa
run_vespa:
	poetry run streamlit run src/demo/apps/vespa/🔍_Retrieval.py
