# -------------------------------------
#  Execution Commands
# -------------------------------------
.PHONY: eda
eda:
	poetry run streamlit run src/demo/apps/eda/📊_Product_Catalogue.py

.PHONY: tokenization
features:
	poetry run streamlit run src/demo/apps/features/🤖_Tokenization.py

.PHONY: es
es:
	poetry run streamlit run src/demo/apps/es/🔍_Retrieval.py

.PHONY: vespa
vespa:
	poetry run streamlit run src/demo/apps/vespa/🔍_Retrieval.py
