[tool.poetry]
name = "amazon-product-search"
version = "0.1.0"
description = ""
authors = ["rejasupotaro"]

[tool.poetry.dependencies]
python = "~3.11"
fugashi = {extras = ["unidic"], version = "^1.2.0"}
ipadic = "^1.0.0"
elasticsearch = "8.16.0"
plotly = "^5.10.0"
tqdm = "^4.64.1"
transformers = "^4.25.1"
sentence-transformers = "^2.3.1"
watchdog = "^2.1.9"
more-itertools = "^9.0.0"
scikit-learn = "^1.2.0"
tabulate = "^0.9.0"
tensorboard = "^2.11.0"
unidic-lite = "^1.0.8"
types-requests = "^2.28.11.17"
docker = "^7.0.0"
dense-retrieval = { path = "../dense-retrieval", develop = true }
gcsfs = "^2023.6.0"
jinja2 = "^3.1.2"
google-cloud-bigquery = {extras = ["pandas"], version = "^3.12.0"}
pyvespa = "^0.39.0"
tritonclient = "^2.41.1"
openai = "^1.14.2"
tenacity = "^8.2.3"
torch = "^2.5.1"
polars = "^1.17.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2"
pytest-cov = "^4.0.0"
optuna = "^3.5.0"
invoke = "^2.2.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
