name: Test Amazon Product Search

on: push

jobs:
  test:
    strategy:
      matrix:
        python-version: ["3.11.8"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Install dependencies
        env:
          SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL: true
        run: |
          uv sync --dev
          uv pip install -e src/data-source
          uv pip install -e src/dense-retrieval  
          uv pip install -e src/amazon-product-search
          uv pip install -e src/indexing
          uv add unidic

      - name: Download unidic dictionary
        run: uv run python -m unidic download

      - name: Run unit tests
        env:
          PYTHONPATH: src/amazon-product-search/src:src/dense-retrieval/src:src/data-source/src
        run: uv run pytest src/amazon-product-search/tests/unit -vv --cov

      # - name: Run integration tests
      #   run: uv run --package amazon-product-search pytest src/amazon-product-search/tests/integration -vv
